name: YML Change Notification Workflow

# This workflow demonstrates how to use the yml-change-webhook action
# to notify external systems when YML files change

on:
  push:
    branches: [ main ]
    paths:
      - 'config/**/*.yml'
      - 'config/**/*.yaml'
  pull_request:
    branches: [ main ]
    paths:
      - 'config/**/*.yml'
      - 'config/**/*.yaml'

jobs:
  notify-changes:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository with enough history for comparisons
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # This is important for accurate Git diff
      
      # Use the yml-change-webhook action to detect changes and trigger webhooks
      - name: Detect YML Changes & Trigger Webhooks
        uses: wearemiew/yml-change-webhook@v1
        with:
          # For pull requests, use the PR base branch for comparison
          base_ref: ${{ github.event.pull_request.base.ref }}
      
      # Optional: Use the output in subsequent steps
      - name: Log changed files
        if: steps.detect-yml-changes.outputs.changed_files != '[]'
        run: |
          echo "The following YML files were changed:"
          echo "${{ steps.detect-yml-changes.outputs.changed_files }}"
