name: Auto-merge Dependabot PRs

# Purpose: Automatically merge dependency updates from Dependabot if tests pass
# Triggered when Dependabot creates or updates a pull request
# This workflow helps maintain up-to-date dependencies with minimal manual intervention

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      
      # Run tests to ensure dependencies don't break anything
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run tests
        run: npm test
      
      # Auto-merge if tests pass
      - name: Auto-merge
        if: success()
        uses: fastify/github-action-merge-dependabot@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: 'squash'
