name: Release
on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run tests
        run: npm test
      
      - name: Build action
        run: npm run build
      
      # Create major version tag
      - name: Update major version tag
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          GITHUB_REF=${{ github.ref }}
          VERSION=${GITHUB_REF#refs/tags/}
          MAJOR=${VERSION%%.*}
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git tag -d "v${MAJOR}" || true
          git push origin ":refs/tags/v${MAJOR}" || true
          git tag "v${MAJOR}" ${{ github.sha }}
          git push origin "v${MAJOR}"
