name: Release
on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run tests
        run: npm test
      
      - name: Build action
        run: npm run build
      
      # Create major and major.minor version tags
      - name: Update version tags
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          GITHUB_REF=${{ github.ref }}
          VERSION=${GITHUB_REF#refs/tags/}
          # Remove 'v' prefix if present
          VERSION_NUM=${VERSION#v}
          
          # Extract version components
          MAJOR=$(echo $VERSION_NUM | cut -d '.' -f 1)
          MINOR=$(echo $VERSION_NUM | cut -d '.' -f 2)
          
          # Setup git
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Create all version tags if the original tag started with 'v'
          if [[ "$VERSION" == v* ]]; then
            # Major version tag (e.g., v1)
            MAJOR_TAG="v$MAJOR"
            git tag -d "$MAJOR_TAG" || true
            git push origin ":refs/tags/$MAJOR_TAG" || true
            git tag "$MAJOR_TAG" ${{ github.sha }}
            git push origin "$MAJOR_TAG"
            echo "Created/updated major version tag: $MAJOR_TAG"
            
            # Major.Minor version tag (e.g., v1.0)
            MAJOR_MINOR_TAG="v$MAJOR.$MINOR"
            git tag -d "$MAJOR_MINOR_TAG" || true
            git push origin ":refs/tags/$MAJOR_MINOR_TAG" || true
            git tag "$MAJOR_MINOR_TAG" ${{ github.sha }}
            git push origin "$MAJOR_MINOR_TAG"
            echo "Created/updated major.minor version tag: $MAJOR_MINOR_TAG"
          fi
