name: Test Action

# Purpose: Runs tests for the action to ensure everything works correctly.
# Triggers:
# - On push to paths affecting functionality
# - On pull request to paths affecting functionality
# Outputs:
# - Test results and build verification

on:
  push:
    paths:
      - "src/**"
      - "**.y{a,}ml"
      - "package*.json"
      - "jest.config.js"
    branches-ignore:
      - "dependabot/**"
      - "docs/**"
  pull_request:
    paths:
      - "src/**"
      - "**.y{a,}ml"
      - "package*.json"
      - "jest.config.js"
    branches:
      - main
      - "feature/**"

# Add concurrency control to prevent multiple workflows from running simultaneously
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    # runs-on: ubuntu-latest
    runs-on:
      labels: [test]
    strategy:
      matrix:
        # node-version: [18.x, 20.x]
        node-version: [20.x]
      fail-fast: false

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Set up Node.js environment with enhanced caching
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: package-lock.json

      # Install Node.js dependencies
      - name: Install dependencies
        run: npm ci

      # Run tests with Jest
      - name: Run tests
        run: NODE_ENV=test npx jest --config jest.config.js --passWithNoTests
        shell: bash

      # Security check for dependencies
      - name: Security audit
        run: npm audit --audit-level=moderate
        continue-on-error: true

      # Don't build the dist directory during testing, only in releases
      # The self-test can still run because it can use the source files directly
      # - name: Build action
      #   run: npm run build

      # Self-test the action (only on push to main and only for Node 20)
      - name: Self-test
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' && matrix.node-version == '20.x'
        uses: ./
        with:
          base_ref: ""

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint
